language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

matrix:
    include:
        - php: 7.1
        - php: 7.2
    fast_finish: true

install:
    - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.12.1/php-cs-fixer.phar -O php-cs-fixer
    - wget http://get.sensiolabs.org/security-checker.phar -O security-checker
    - wget https://github.com/phpstan/phpstan/releases/download/0.9.2/phpstan.phar -O phpstan

script:
  - make dev-check
  - make dev-init
  - make phpunit

branches:
  only:
      - master
